/*
 * This file was automatically generated by EvoSuite
 * Thu Jul 26 17:24:26 GMT 2018
 */
package com.tsi.workflow.activity;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

import com.tsi.workflow.DataWareHouse;
import com.tsi.workflow.User;
import com.tsi.workflow.base.IBeans;
import com.tsi.workflow.beans.dao.ImpPlan;
import com.tsi.workflow.beans.dao.Implementation;
import com.tsi.workflow.beans.dao.SystemLoad;
import org.junit.Test;

public class ProdFTPActivityMessageTest {

    @Test(timeout = 4000)
    public void test00() throws Throwable {
	ImpPlan impPlan0 = new ImpPlan();
	IBeans[] iBeansArray0 = new IBeans[6];
	ProdFTPActivityMessage prodFTPActivityMessage0 = new ProdFTPActivityMessage(impPlan0, (Implementation) null, iBeansArray0);
	User user0 = new User();
	prodFTPActivityMessage0.setUser(user0);
	SystemLoad systemLoad0 = new SystemLoad();
	prodFTPActivityMessage0.lBuild = systemLoad0;
	// Undeclared exception!
	try {
	    prodFTPActivityMessage0.processMessage();
	    fail("Expecting exception: NullPointerException");

	} catch (NullPointerException e) {
	}
    }

    @Test(timeout = 4000)
    public void test01() throws Throwable {
	ImpPlan impPlan0 = new ImpPlan();
	IBeans[] iBeansArray0 = new IBeans[7];
	ProdFTPActivityMessage prodFTPActivityMessage0 = new ProdFTPActivityMessage(impPlan0, (Implementation) null, iBeansArray0);
	User user0 = new User("");
	Integer integer0 = new Integer(70);
	SystemLoad systemLoad0 = new SystemLoad(integer0);
	prodFTPActivityMessage0.lBuild = systemLoad0;
	user0.setCurrentDelegatedUser(user0);
	prodFTPActivityMessage0.setUser(user0);
	// Undeclared exception!
	try {
	    prodFTPActivityMessage0.processMessage();
	    fail("Expecting exception: NullPointerException");

	} catch (NullPointerException e) {
	}
    }

    @Test(timeout = 4000)
    public void test02() throws Throwable {
	ImpPlan impPlan0 = new ImpPlan();
	IBeans[] iBeansArray0 = new IBeans[7];
	ProdFTPActivityMessage prodFTPActivityMessage0 = new ProdFTPActivityMessage(impPlan0, (Implementation) null, iBeansArray0);
	User user0 = new User("");
	prodFTPActivityMessage0.setUser(user0);
	prodFTPActivityMessage0.setFallback(true);
	SystemLoad systemLoad0 = new SystemLoad();
	prodFTPActivityMessage0.lBuild = systemLoad0;
	// Undeclared exception!
	try {
	    prodFTPActivityMessage0.processMessage();
	    fail("Expecting exception: NullPointerException");

	} catch (NullPointerException e) {
	}
    }

    @Test(timeout = 4000)
    public void test03() throws Throwable {
	IBeans[] iBeansArray0 = new IBeans[1];
	ProdFTPActivityMessage prodFTPActivityMessage0 = new ProdFTPActivityMessage((ImpPlan) null, (Implementation) null, iBeansArray0);
	prodFTPActivityMessage0.setFallback(true);
	boolean boolean0 = prodFTPActivityMessage0.isFallback();
	assertTrue(boolean0);
    }

    @Test(timeout = 4000)
    public void test04() throws Throwable {
	ImpPlan impPlan0 = new ImpPlan();
	Implementation implementation0 = new Implementation();
	ProdFTPActivityMessage prodFTPActivityMessage0 = new ProdFTPActivityMessage(impPlan0, implementation0, (IBeans[]) null);
	prodFTPActivityMessage0.setStatus((String) null);
	String string0 = prodFTPActivityMessage0.getStatus();
	assertNull(string0);
    }

    @Test(timeout = 4000)
    public void test05() throws Throwable {
	ImpPlan impPlan0 = new ImpPlan();
	IBeans[] iBeansArray0 = new IBeans[7];
	ProdFTPActivityMessage prodFTPActivityMessage0 = new ProdFTPActivityMessage(impPlan0, (Implementation) null, iBeansArray0);
	assertEquals("Started", prodFTPActivityMessage0.getStatus());

	prodFTPActivityMessage0.setStatus("");
	String string0 = prodFTPActivityMessage0.getStatus();
	assertNotNull(string0);
	assertEquals("", string0);
    }

    @Test(timeout = 4000)
    public void test06() throws Throwable {
	IBeans[] iBeansArray0 = new IBeans[3];
	ProdFTPActivityMessage prodFTPActivityMessage0 = new ProdFTPActivityMessage((ImpPlan) null, (Implementation) null, iBeansArray0);
	prodFTPActivityMessage0.setIpAddress("Fallback Loadset for the plan {2} - {0} has uploaded {5} the loadset {1}, system {3} to the IP Address {4}, on behalf of {6} ");
	String string0 = prodFTPActivityMessage0.getIpAddress();
	assertEquals("Fallback Loadset for the plan {2} - {0} has uploaded {5} the loadset {1}, system {3} to the IP Address {4}, on behalf of {6} ", string0);
	assertNotNull(string0);
	assertEquals("Started", prodFTPActivityMessage0.getStatus());
    }

    @Test(timeout = 4000)
    public void test07() throws Throwable {
	IBeans[] iBeansArray0 = new IBeans[5];
	ProdFTPActivityMessage prodFTPActivityMessage0 = new ProdFTPActivityMessage((ImpPlan) null, (Implementation) null, iBeansArray0);
	prodFTPActivityMessage0.ipAddress = "";
	String string0 = prodFTPActivityMessage0.getIpAddress();
	assertEquals("Started", prodFTPActivityMessage0.getStatus());
	assertEquals("", string0);
    }

    @Test(timeout = 4000)
    public void test08() throws Throwable {
	ImpPlan impPlan0 = new ImpPlan();
	Implementation implementation0 = new Implementation();
	ProdFTPActivityMessage prodFTPActivityMessage0 = new ProdFTPActivityMessage(impPlan0, implementation0, (IBeans[]) null);
	// Undeclared exception!
	try {
	    prodFTPActivityMessage0.setArguments((IBeans[]) null);
	    fail("Expecting exception: NullPointerException");

	} catch (NullPointerException e) {
	}
    }

    @Test(timeout = 4000)
    public void test09() throws Throwable {
	ImpPlan impPlan0 = new ImpPlan();
	Implementation implementation0 = new Implementation("_(ap");
	ProdFTPActivityMessage prodFTPActivityMessage0 = new ProdFTPActivityMessage(impPlan0, implementation0, (IBeans[]) null);
	IBeans[] iBeansArray0 = new IBeans[0];
	// Undeclared exception!
	try {
	    prodFTPActivityMessage0.setArguments(iBeansArray0);
	    fail("Expecting exception: ArrayIndexOutOfBoundsException");

	} catch (ArrayIndexOutOfBoundsException e) {
	}
    }

    @Test(timeout = 4000)
    public void test10() throws Throwable {
	Implementation implementation0 = new Implementation();
	IBeans[] iBeansArray0 = new IBeans[0];
	ProdFTPActivityMessage prodFTPActivityMessage0 = null;
	try {
	    prodFTPActivityMessage0 = new ProdFTPActivityMessage((ImpPlan) null, implementation0, iBeansArray0);
	    fail("Expecting exception: ArrayIndexOutOfBoundsException");

	} catch (ArrayIndexOutOfBoundsException e) {
	}
    }

    @Test(timeout = 4000)
    public void test11() throws Throwable {
	IBeans[] iBeansArray0 = new IBeans[1];
	ProdFTPActivityMessage prodFTPActivityMessage0 = new ProdFTPActivityMessage((ImpPlan) null, (Implementation) null, iBeansArray0);
	prodFTPActivityMessage0.isFallback();
	assertEquals("Started", prodFTPActivityMessage0.getStatus());
    }

    @Test(timeout = 4000)
    public void test12() throws Throwable {
	IBeans[] iBeansArray0 = new IBeans[1];
	ProdFTPActivityMessage prodFTPActivityMessage0 = new ProdFTPActivityMessage((ImpPlan) null, (Implementation) null, iBeansArray0);
	prodFTPActivityMessage0.setArguments(iBeansArray0);
	assertEquals("Started", prodFTPActivityMessage0.getStatus());
    }

    @Test(timeout = 4000)
    public void test13() throws Throwable {
	IBeans[] iBeansArray0 = new IBeans[7];
	ProdFTPActivityMessage prodFTPActivityMessage0 = new ProdFTPActivityMessage((ImpPlan) null, (Implementation) null, iBeansArray0);
	User user0 = new User(" does not support them");
	user0.setCurrentDelegatedUser(user0);
	prodFTPActivityMessage0.setUser(user0);
	prodFTPActivityMessage0.setFallback(true);
	// Undeclared exception!
	try {
	    prodFTPActivityMessage0.processMessage();
	    fail("Expecting exception: NullPointerException");

	} catch (NullPointerException e) {
	}
    }

    @Test(timeout = 4000)
    public void test14() throws Throwable {
	Implementation implementation0 = new Implementation();
	IBeans[] iBeansArray0 = new IBeans[3];
	ProdFTPActivityMessage prodFTPActivityMessage0 = new ProdFTPActivityMessage((ImpPlan) null, implementation0, iBeansArray0);
	prodFTPActivityMessage0.getLogLevel();
	assertEquals("Started", prodFTPActivityMessage0.getStatus());
    }

    @Test(timeout = 4000)
    public void test15() throws Throwable {
	ImpPlan impPlan0 = new ImpPlan();
	Implementation implementation0 = new Implementation();
	IBeans[] iBeansArray0 = new IBeans[7];
	ProdFTPActivityMessage prodFTPActivityMessage0 = new ProdFTPActivityMessage(impPlan0, implementation0, iBeansArray0);
	String string0 = prodFTPActivityMessage0.getStatus();
	assertEquals("Started", string0);
	assertNotNull(string0);
    }

    @Test(timeout = 4000)
    public void test16() throws Throwable {
	IBeans[] iBeansArray0 = new IBeans[4];
	ProdFTPActivityMessage prodFTPActivityMessage0 = new ProdFTPActivityMessage((ImpPlan) null, (Implementation) null, iBeansArray0);
	String string0 = prodFTPActivityMessage0.getIpAddress();
	assertEquals("Started", prodFTPActivityMessage0.getStatus());
	assertNull(string0);
    }

    @Test
    public void testProcessMessage() {
	SystemLoad sysLoad = DataWareHouse.getPlan().getSystemLoadList().get(0);
	sysLoad.setFallbackLoadSetName("loadSetFall");
	sysLoad.setLoadSetName("loadSet");
	IBeans[] iBeansArray0 = new IBeans[4];
	ImpPlan impPlan = new ImpPlan();
	impPlan.setId("100");
	ProdFTPActivityMessage instance = new ProdFTPActivityMessage(impPlan, (Implementation) null, iBeansArray0);
	instance.setArguments(sysLoad);
	User usr = DataWareHouse.getUser();
	usr.setCurrentDelegatedUser(usr);
	instance.setUser(usr);
	instance.setFallback(Boolean.TRUE);
	instance.processMessage();

    }
}
