//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.28 at 02:50:50 PM IST 
//

package com.tsi.workflow.gi.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "projName", "platform", "target", "processingType", "configFile" })
@XmlRootElement(name = "Project-Create")
public class ProjectCreate {

    @XmlElement(name = "ProjName", required = true)
    protected String projName;
    @XmlElement(name = "Platform", required = true)
    protected String platform;
    @XmlElement(name = "Target", required = true)
    protected String target;
    @XmlElement(name = "ProcessingType", required = true)
    protected String processingType;
    @XmlElement(name = "ConfigFile")
    protected ConfigFile configFile;

    /**
     * Gets the value of the projName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getProjName() {
	return projName;
    }

    /**
     * Sets the value of the projName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setProjName(String value) {
	this.projName = value;
    }

    /**
     * Gets the value of the platform property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPlatform() {
	return platform;
    }

    /**
     * Sets the value of the platform property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setPlatform(String value) {
	this.platform = value;
    }

    /**
     * Gets the value of the target property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTarget() {
	return target;
    }

    /**
     * Sets the value of the target property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTarget(String value) {
	this.target = value;
    }

    /**
     * Gets the value of the processingType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getProcessingType() {
	return processingType;
    }

    /**
     * Sets the value of the processingType property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setProcessingType(String value) {
	this.processingType = value;
    }

    /**
     * Gets the value of the configFile property.
     * 
     * @return possible object is {@link ConfigFile }
     * 
     */
    public ConfigFile getConfigFile() {
	return configFile;
    }

    /**
     * Sets the value of the configFile property.
     * 
     * @param value
     *            allowed object is {@link ConfigFile }
     * 
     */
    public void setConfigFile(ConfigFile value) {
	this.configFile = value;
    }

}
