//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.28 at 02:50:50 PM IST 
//

package com.tsi.workflow.gi.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "empty" })
@XmlRootElement(name = "Projects-List")
public class ProjectsList {

    @XmlElement(name = "EMPTY", required = true)
    protected EMPTY empty;

    /**
     * Gets the value of the empty property.
     * 
     * @return possible object is {@link EMPTY }
     * 
     */
    public EMPTY getEMPTY() {
	return empty;
    }

    /**
     * Sets the value of the empty property.
     * 
     * @param value
     *            allowed object is {@link EMPTY }
     * 
     */
    public void setEMPTY(EMPTY value) {
	this.empty = value;
    }

}
