//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.06.28 at 02:50:50 PM IST
//
package com.tsi.workflow.gi.request;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "projectCreateOrProjectAddDirRuleOrProjectAddFileRuleOrProjectRefreshOrProjectDeleteOrProjectsListOrProjectSetTargetOrFilesOpenFile" })
@XmlRootElement(name = "Service")
public class Service {

    @XmlElements({ @XmlElement(name = "Project-Create", required = true, type = ProjectCreate.class), @XmlElement(name = "Project-AddDirRule", required = true, type = ProjectAddDirRule.class), @XmlElement(name = "Project-AddFileRule", required = true, type = ProjectAddFileRule.class), @XmlElement(name = "Project-Refresh", required = true, type = ProjectRefresh.class), @XmlElement(name = "Project-Delete", required = true, type = ProjectDelete.class),
	    @XmlElement(name = "Projects-List", required = true, type = ProjectsList.class), @XmlElement(name = "Project-SetTarget", required = true, type = ProjectSetTarget.class), @XmlElement(name = "Files-OpenFile", required = true, type = FilesOpenFile.class) })
    protected List<Object> projectCreateOrProjectAddDirRuleOrProjectAddFileRuleOrProjectRefreshOrProjectDeleteOrProjectsListOrProjectSetTargetOrFilesOpenFile;

    /**
     * Gets the value of the
     * projectCreateOrProjectAddDirRuleOrProjectAddFileRuleOrProjectRefreshOrProjectDeleteOrProjectsListOrProjectSetTargetOrFilesOpenFile
     * property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot.
     * Therefore any modification you make to the returned list will be present
     * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
     * for the
     * projectCreateOrProjectAddDirRuleOrProjectAddFileRuleOrProjectRefreshOrProjectDeleteOrProjectsListOrProjectSetTargetOrFilesOpenFile
     * property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getProjectCreateOrProjectAddDirRuleOrProjectAddFileRuleOrProjectRefreshOrProjectDeleteOrProjectsListOrProjectSetTargetOrFilesOpenFile().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list {@link ProjectCreate
     * } {@link ProjectAddDirRule } {@link ProjectAddFileRule }
     * {@link ProjectRefresh } {@link ProjectDelete } {@link ProjectsList }
     * {@link ProjectSetTarget } {@link FilesOpenFile }
     *
     *
     */
    public List<Object> getProjectCreateOrProjectAddDirRuleOrProjectAddFileRuleOrProjectRefreshOrProjectDeleteOrProjectsListOrProjectSetTargetOrFilesOpenFile() {
	if (projectCreateOrProjectAddDirRuleOrProjectAddFileRuleOrProjectRefreshOrProjectDeleteOrProjectsListOrProjectSetTargetOrFilesOpenFile == null) {
	    projectCreateOrProjectAddDirRuleOrProjectAddFileRuleOrProjectRefreshOrProjectDeleteOrProjectsListOrProjectSetTargetOrFilesOpenFile = new ArrayList<Object>();
	}
	return this.projectCreateOrProjectAddDirRuleOrProjectAddFileRuleOrProjectRefreshOrProjectDeleteOrProjectsListOrProjectSetTargetOrFilesOpenFile;
    }

}
