//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.28 at 02:51:03 PM IST 
//

package com.tsi.workflow.gi.response;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "projName", "platform", "target", "processingType", "configFile", "dirRule", "fileRule" })
@XmlRootElement(name = "Project")
public class Project {

    @XmlElement(name = "ProjName", required = true)
    protected String projName;
    @XmlElement(name = "Platform", required = true)
    protected String platform;
    @XmlElement(name = "Target", required = true)
    protected String target;
    @XmlElement(name = "ProcessingType", required = true)
    protected String processingType;
    @XmlElement(name = "ConfigFile", required = true)
    protected ConfigFile configFile;
    @XmlElement(name = "DirRule")
    protected List<DirRule> dirRule;
    @XmlElement(name = "FileRule")
    protected List<FileRule> fileRule;

    /**
     * Gets the value of the projName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getProjName() {
	return projName;
    }

    /**
     * Sets the value of the projName property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setProjName(String value) {
	this.projName = value;
    }

    /**
     * Gets the value of the platform property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPlatform() {
	return platform;
    }

    /**
     * Sets the value of the platform property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setPlatform(String value) {
	this.platform = value;
    }

    /**
     * Gets the value of the target property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTarget() {
	return target;
    }

    /**
     * Sets the value of the target property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTarget(String value) {
	this.target = value;
    }

    /**
     * Gets the value of the processingType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getProcessingType() {
	return processingType;
    }

    /**
     * Sets the value of the processingType property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setProcessingType(String value) {
	this.processingType = value;
    }

    /**
     * Gets the value of the configFile property.
     * 
     * @return possible object is {@link ConfigFile }
     * 
     */
    public ConfigFile getConfigFile() {
	return configFile;
    }

    /**
     * Sets the value of the configFile property.
     * 
     * @param value
     *            allowed object is {@link ConfigFile }
     * 
     */
    public void setConfigFile(ConfigFile value) {
	this.configFile = value;
    }

    /**
     * Gets the value of the dirRule property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot.
     * Therefore any modification you make to the returned list will be present
     * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
     * for the dirRule property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getDirRule().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link DirRule }
     * 
     * 
     */
    public List<DirRule> getDirRule() {
	if (dirRule == null) {
	    dirRule = new ArrayList<DirRule>();
	}
	return this.dirRule;
    }

    /**
     * Gets the value of the fileRule property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot.
     * Therefore any modification you make to the returned list will be present
     * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
     * for the fileRule property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getFileRule().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link FileRule }
     * 
     * 
     */
    public List<FileRule> getFileRule() {
	if (fileRule == null) {
	    fileRule = new ArrayList<FileRule>();
	}
	return this.fileRule;
    }

}
