/*
 * This file was automatically generated by EvoSuite
 * Tue Aug 07 10:27:51 GMT 2018
 */

package com.tsi.workflow.mail;

import static org.junit.Assert.*;

import java.util.LinkedList;
import org.junit.Test;

public class AccessPermissionMailTest {

    @Test
    public void test18() throws Throwable {
	AccessPermissionMail accessPermissionMail0 = new AccessPermissionMail();
	Boolean boolean0 = Boolean.valueOf(false);
	accessPermissionMail0.setIsAdded(boolean0);
	LinkedList<String> linkedList0 = new LinkedList<String>();
	linkedList0.addLast("/cPc{exh#!");
	accessPermissionMail0.setUserList(linkedList0);
	accessPermissionMail0.processMessage();
	assertEquals("Users updated with repository -  null", accessPermissionMail0.getSubject());
    }

    @Test
    public void test19() throws Throwable {
	AccessPermissionMail accessPermissionMail0 = new AccessPermissionMail();
	LinkedList<String> linkedList0 = new LinkedList<String>();
	linkedList0.add("ACTIVATED");
	accessPermissionMail0.setUserList(linkedList0);
	Boolean boolean0 = Boolean.valueOf("ACTIVATED");
	accessPermissionMail0.setIsUserMail(boolean0);
	Boolean boolean1 = Boolean.TRUE;
	accessPermissionMail0.setIsAdded(boolean1);
	accessPermissionMail0.processMessage();
	assertEquals("The following users has been added to Repository null  by dev manager null with the below permissions:<br>ACTIVATED:null", accessPermissionMail0.getMessage());
	assertEquals("Users added to repository -  null", accessPermissionMail0.getSubject());
    }

    @Test
    public void test20() throws Throwable {
	AccessPermissionMail accessPermissionMail0 = new AccessPermissionMail();
	Boolean boolean0 = Boolean.valueOf("ACTIVATED");
	accessPermissionMail0.setIsUserMail(boolean0);
	Boolean boolean1 = Boolean.TRUE;
	accessPermissionMail0.setIsAdded(boolean1);
	LinkedList<String> linkedList0 = new LinkedList<String>();
	linkedList0.add("ACTIVATED");
	accessPermissionMail0.setUserList(linkedList0);
	// Undeclared exception!
	try {
	    accessPermissionMail0.processMessage();

	} catch (NullPointerException e) {
	    //
	    // no message in exception (getMessage() returned null)
	    //
	}
    }

    @Test
    public void test21() throws Throwable {
	AccessPermissionMail accessPermissionMail0 = new AccessPermissionMail();
	LinkedList<String> linkedList0 = new LinkedList<String>();
	Boolean boolean0 = Boolean.TRUE;
	accessPermissionMail0.setIsAdded(boolean0);
	accessPermissionMail0.setIsUserMail(boolean0);
	accessPermissionMail0.setUserList(linkedList0);
	accessPermissionMail0.processMessage();
	assertEquals("Users  added to repository -  null", accessPermissionMail0.getSubject());
    }

    @Test
    public void processTest() {
	AccessPermissionMail accessPermissionInstance = new AccessPermissionMail();
	accessPermissionInstance.setIsAdded(Boolean.FALSE);
	accessPermissionInstance.setIsUserMail(Boolean.TRUE);
	LinkedList<String> linkedList0 = new LinkedList<String>();
	accessPermissionInstance.setUserList(linkedList0);
	accessPermissionInstance.setRepoName("DevOpe");
	accessPermissionInstance.setRepoPermission("allow");
	accessPermissionInstance.setDevManager("mgr");
	accessPermissionInstance.processMessage();
    }

    // @Test
    public void test22() throws Throwable {
	AccessPermissionMail accessPermissionMail0 = new AccessPermissionMail();
	accessPermissionMail0.setIsUserMail(true);
	accessPermissionMail0.setIsAdded(false);
	LinkedList<String> linkedList0 = new LinkedList<String>();
	accessPermissionMail0.setUserList(linkedList0);
	// Undeclared exception!
	try {
	    accessPermissionMail0.processMessage();
	    fail("Expecting exception: NullPointerException");

	} catch (NullPointerException e) {
	    //
	    // no message in exception (getMessage() returned null)
	    //
	}
    }

    // @Test
    public void test23() throws Throwable {
	AccessPermissionMail accessPermissionMail0 = new AccessPermissionMail();
	accessPermissionMail0.setIsUserMail(false);
	accessPermissionMail0.setIsAdded(false);
	LinkedList<String> linkedList0 = new LinkedList<String>();
	accessPermissionMail0.setUserList(linkedList0);
	// Undeclared exception!
	try {
	    accessPermissionMail0.processMessage();
	    fail("Expecting exception: NullPointerException");

	} catch (NullPointerException e) {
	    //
	    // no message in exception (getMessage() returned null)
	    //
	}

    }
}
