/*
 * This file was automatically generated by EvoSuite
 * Thu Aug 09 04:48:10 GMT 2018
 */

package com.tsi.workflow.mail;

import static org.junit.Assert.*;

import com.tsi.workflow.MailConfig;
import com.tsi.workflow.interfaces.IMailConfig;
import com.workflow.mail.AzureMailUtil;
import org.junit.Test;

public class AzureMailUtilTest {

    @Test(timeout = 4000)
    public void test0() throws Throwable {
	MailConfig mailConfig0 = new MailConfig();
	AzureMailUtil azureMailUtil0 = null;
	try {
	    azureMailUtil0 = new AzureMailUtil(mailConfig0);
	    fail("Expecting exception: IllegalArgumentException");

	} catch (IllegalArgumentException e) {
	    //
	    // Invalid url
	    //
	}
    }

    @Test(timeout = 4000)
    public void test1() throws Throwable {
	AzureMailUtil azureMailUtil0 = null;
	try {
	    azureMailUtil0 = new AzureMailUtil((IMailConfig) null);
	    fail("Expecting exception: NullPointerException");

	} catch (NullPointerException e) {
	    //
	    // no message in exception (getMessage() returned null)
	    //
	}
    }
}
