/*
 * This file was automatically generated by EvoSuite
 * Thu Aug 09 05:00:47 GMT 2018
 */

package com.tsi.workflow.cache;

import static org.junit.Assert.*;
import static org.junit.Assert.fail;
import static org.mockito.Mockito.spy;

import com.hazelcast.core.Member;
import com.hazelcast.core.Message;
import com.hazelcast.instance.MemberImpl;
import com.tsi.workflow.WFConfig;
import com.tsi.workflow.helper.DelegateHelper;
import com.tsi.workflow.helper.RejectHelperTest;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;

public class DelegateCacheListenerTest {

    @InjectMocks
    private WFConfig wFConfig;

    public DelegateCacheListenerTest() {
    }

    @BeforeClass
    public static void setUpClass() {
    }

    @AfterClass
    public static void tearDownClass() {
    }

    @Before
    public void setUp() {
	try {
	    DelegateCacheListener realInstance = new DelegateCacheListener(null, null);
	    instance = spy(realInstance);
	    wFConfig = new WFConfig();
	} catch (Exception ex) {
	    Logger.getLogger(RejectHelperTest.class.getName()).log(Level.SEVERE, null, ex);
	    fail("Fail on Exception " + ex.getMessage());
	}
    }

    private DelegateCacheListener instance;
    @Mock
    private Message message;

    @After
    public void tearDown() {
    }

    // @Test
    public void test() {
	instance.onMessage(message);
    }

    @Test(timeout = 4000)
    public void test0() throws Throwable {
	WFConfig wFConfig0 = new WFConfig();
	DelegateCacheListener delegateCacheListener0 = new DelegateCacheListener(wFConfig0, (DelegateHelper) null);
	Message<String> message0 = new Message<String>("", "", (-2073L), (Member) null);
	// Undeclared exception!
	try {
	    delegateCacheListener0.onMessage(message0);
	    fail("Expecting exception: NullPointerException");

	} catch (NullPointerException e) {
	    //
	    // no message in exception (getMessage() returned null)
	    //
	}
    }

    @Test(timeout = 4000)
    public void test1() throws Throwable {
	WFConfig wFConfig0 = new WFConfig();
	DelegateCacheListener delegateCacheListener0 = new DelegateCacheListener(wFConfig0, (DelegateHelper) null);
	MemberImpl memberImpl0 = new MemberImpl();
	Message<String> message0 = new Message<String>("", "\"cV'#T~bt", (-2071L), memberImpl0);
	// Undeclared exception!
	try {
	    delegateCacheListener0.onMessage(message0);
	    fail("Expecting exception: RuntimeException");

	} catch (RuntimeException e) {
	    //
	    // org.evosuite.runtime.mock.java.lang.MockThrowable: Expected BEGIN_OBJECT but
	    // was STRING at line 1 column
	    // 2 path $
	    //
	}
    }
}
